module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- For more details, see http://developer.anscamobile.com/reference/sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "m2.png",
				spriteColorRect = { x = 0, y = 0, width = 301, height = 300 }, 
				textureRect = { x = 0, y = 302, width = 301, height = 300 }, 
				spriteSourceSize = { width = 301, height = 300 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "m1.png",
				spriteColorRect = { x = 0, y = 0, width = 301, height = 300 }, 
				textureRect = { x = 0, y = 0, width = 301, height = 300 }, 
				spriteSourceSize = { width = 301, height = 300 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end